.TH texfindpkg 1 "2023-04-05" "2023D"
.SH NAME
TexFindPkg \- Install TeX packages and their dependencies
.SH SYNOPSIS
texfindpkg <action> [<options>] [<name>]
.SH DESCRIPTION
TeXFindPkg makes it easy to install TeX packages and their dependencies
by file names, command names or environment names.
.PP
The most commonly used TeXFindPkg actions are:
.IP install
Install some package and its dependencies
.IP query
Query dependencies for some package
.SH OPTIONS
Various options apply
.IP --help
Print a help message and exit
.IP --version
Print version information and exit
.SH BUGS
.SH AUTHOR
Jianrui Lyu <tolvjr@163.com>
.PP
Please log issues on the GitHub homepage:
https://github.com/lvjr/texfindpkg/issues.
