.TH texfindpkg 1 "2024-11-22" "2024A"
.SH NAME
TexFindPkg \- Query or install TeX packages and their dependencies
.SH SYNOPSIS
texfindpkg <action> [<option>] [<name>]
.SH DESCRIPTION
TeXFindPkg tool makes it easy to query or install some TeX packages and
their dependencies by file names, command names or environment names.
.PP
The most commonly used TeXFindPkg actions are:
.IP "query, \-\-query" 6
Query dependencies for some package
.IP "install, \-\-install" 6
Install some package and its dependencies
.IP "help, \-\-help" 6
Print a help message and exit
.IP "version, \-\-version" 6
Print version information and exit
.SH OPTIONS
Various options apply
.IP -c 6
Query or install packages by command name
.IP -e 6
Query or install packages by environment name
.IP -f 6
Query or install packages by file name
.IP -p 6
Query or install packages by package name
.SH BUGS
Please log issues on
https://github.com/lvjr/texfindpkg/issues
